### PR TITLE
v3.3.0

### PR DESCRIPTION
**Pull request by jeremy-coulon**

### CODE REVIEW

**Comment by jeremy-coulon** [comment]
AppVeyor thinks I am trying to build v3.6.1 and fails because v3.6.1!=v3.3.0.
Is that because I am trying to merge into stable/3.6.1 branch ? 
How do I tell it to create a new branch 'testing/3.3.0' ?

**Comment by Croydon** [comment]
You can't create new branch targets without our repositories, you can only target branches which do already exist. 

@uilianries Do you think it is reasonable to add older versions, as we are kinda already struggling with the more recent ones?

**Comment by uilianries** [comment]
well, if @jeremy-coulon needs protobuf 3.3.0 and could help us, I see no problem, but we will need provide the installer package too.

**Comment by uilianries** [comment]
@jeremy-coulon Done! Also, I've rebased your branch to testing/3.3.0

**Pull request merged**
