### PR TITLE
Update to protobuf 3.11.4 version

### PR DESCRIPTION
**Pull request by schreibubi**
Updated the patches to apply to 3.11.4

### CODE REVIEW

**Comment by Croydon** [comment]
I think we want to wait until https://github.com/conan-io/conan-center-index/pull/1179 is landed and not add any new versions here

**Comment by schreibubi** [comment]
Hi,

seems like that issue has been stale for 2 months now. Protobuf without protoc is of not a lot of use to anyone.

**Comment by Croydon** [comment]
Now it is merged 😄

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

**Pull request closed without merging**
